### ISSUE TITLE
Changing Modpack versions

### ISSUE THREAD

**Issue by NillerMedDild** [HearthProject/OneClient#11]
It would be handy, if it was possible to choose between the various versions of modpacks, under the "Change Version" tab of the instance:

![billede](https://user-images.githubusercontent.com/21295394/29685473-e5805102-8915-11e7-9ca8-fb7e5688cee4.png)

**Comment by modmuss50** [comment]
Yeah, thats a good idea, I should also add a way to check/show updates as well.

**Comment by NillerMedDild** [comment]
Yeah - preferably a check while the launcher begins, so you realize you need to update, before launching the game.

**Comment by modmuss50** [comment]
Its now in.

**Comment by NillerMedDild** [comment]
Thank you, the OneClient is shaping out nicely :D
