### ISSUE TITLE
Unable to find ZIP to download

### ISSUE THREAD

**Issue by NillerMedDild** [HearthProject/OneClient#19]
I tried installing the pack Enigmatica 2, but the OneClient is unable to find the file to download
[log](https://gist.github.com/NillerMedDild/fa9b4af638bdd8bd3d111b892b6be16b)
[Link](https://minecraft.curseforge.com/projects/enigmatica2/files/2465595) to the zip file it should download

Edit: Now it works, the only thing I did was navigate back and forth a few times - I'll leave this issue open for a bit, in case you want the log.

**Comment by NillerMedDild** [comment]
Navigating from the overview of the pack, to a different tab and back to overview allows the download to start properly - So I guess the Install button doesn't get properly set when first visiting the pack.
I'm going to try and reproduce it on other packs.

**Comment by MrPatience** [comment]
After some trying out on differents platforms/ OS : 
-Searching with curseforge search tool , then clicking on chosen modpack (for instance Space Astronomy 2) leads to that page 
https://minecraft.curseforge.com/projects/space-astronomy-2?gameCategorySlug=modpacks&projectID=270372
CMPDL doesn't understand what's past the ? (all the query) and gets unknown pack.
using this 
https://minecraft.curseforge.com/projects/space-astronomy-2
(obtained on oneclient by going to the files , then back to overview)
works just fine.=)

**Comment by modmuss50** [comment]
Can you guys try on the latest version? And let me know if this is still an issue?

**Comment by NillerMedDild** [comment]
It's fixed, thanks! :D
