### ISSUE TITLE
some packs still dont load

### ISSUE THREAD

**Issue by modmuss50** [HearthProject/OneClient#21]
1.7.10 https://gist.github.com/NillerMedDild/9a54e799a35f6e1c963ef2cd268c84c7

Enigmatica 2 crashes in our launcher, but not in twitch, log: https://gist.github.com/NillerMedDild/0d5cc8c4db0ecf3fb18a6d91586f58a4

**Comment by NillerMedDild** [comment]
Enigmatica 2 no longer crashes, good work :D
