### ISSUE TITLE
Skin and account information aren't loading correctly

### ISSUE THREAD

**Issue by neclimdul** [HearthProject/OneClient#22]
It seems like there is some sort of problem with the authentication or account information connected to the Minecraft instance.

Currently I'm not able to see my skin. Tested in 1.10 modpack and vanilla 1.12.1.

Additionally when playing a modpack like AoE the FTB team system isn't working correctly. Says you're not a member of a team, teams ui won't load, and you can't interact with blocks in your teams chunks.

**Comment by modmuss50** [comment]
Humm thats very strange
