### ISSUE TITLE
Incorrect Modpack Name

### ISSUE THREAD

**Issue by NillerMedDild** [HearthProject/OneClient#23]
Hey!

The name the OneClient picks for a new instance, isn't always correct. In the picture, the pack "Enigmatica 2" was named "Enigmatica 1.12.1 Tester" - Which happens to be the name of the Instance I uploaded the Export Profile from, which seems a bit... concerning.

![billede](https://user-images.githubusercontent.com/21295394/29744496-09a5a00a-8aa6-11e7-99c4-8157cc92d652.png)

**Comment by modmuss50** [comment]
The instance name is generated from the name provided in the manifest file contained within the zip file. I dont really see what is wrong here?

**Comment by NillerMedDild** [comment]
It must be my mistake in that case, I just find it odd, as the default name is "Enigmatica 2".
