### ISSUE TITLE
Make the RAM allocation slider less accurate and/or add a field for it

### ISSUE THREAD

**Issue by slaugaus** [HearthProject/OneClient#30]
I don't think anyone needs precision down to 0.01 GB. In comparison, Twitch's slider goes in 256MB steps.

**Comment by primetoxinz** [comment]
Replaced with this in development.
![one client_026](https://user-images.githubusercontent.com/4721642/29901722-83836d8e-8dc7-11e7-8638-e135770c5295.png)
