### ISSUE TITLE
ZIP pack installs hang if a mod link doesn't work

### ISSUE THREAD

**Issue by slaugaus** [HearthProject/OneClient#32]
[This ZIP for Modern Skyblock 2](https://minecraft.curseforge.com/projects/modern-skyblock-2/files/2468690) links to [a HarvestCraft version that was pulled](https://minecraft.curseforge.com/projects/pams-harvestcraft/files/2468552/download), which caused the error below and made the installer stop. Doing it through the integrated CMPDL throws a warning, but the install continues.

![untitled](https://user-images.githubusercontent.com/23143819/29745655-e8ef0f3e-8a75-11e7-9053-c750eab0d92f.png)

**Comment by modmuss50** [comment]
Can you try again, and let me know if this is still an issue?

**Comment by slaugaus** [comment]
I don't see any way to import directly from a ZIP anymore, so it's not an issue.
