### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by primetoxinz** [HearthProject/OneClient#34]

**Comment by jjenco** [comment]
Can confirm, I left OneClient up for roughly 4 hours just idling, and it's using 1.5GB of RAM at the moment
![oneclient ram usage](https://user-images.githubusercontent.com/30219540/29747401-f73ed2dc-8abf-11e7-8115-80fd2fd95732.png)

**Comment by jjenco** [comment]
Seems like this might've been fixed in the current build.  I left the launcher open for a few hours again, and it's only using about 120MB of RAM, even after browsing through Curse modpacks and installing and uninstalling a few instances

**Comment by primetoxinz** [comment]
I'll close then, if it happens again just open another issue.
