### ISSUE TITLE
OneClient crash

### ISSUE THREAD

**Issue by Kileahh** [HearthProject/OneClient#65]
I was testing one client and it crashes, I don't really remember what I was doing between try to import from twitch, or try to get the mod list from curse.

[Log file](https://github.com/HearthProject/OneClient/files/1330409/2017-09-26-1.log)

**Comment by primetoxinz** [comment]
You were on a network that doesn't allow access to curse or your internet went down, either way this shouldn't be directly our fault.

**Comment by Kileahh** [comment]
I think it's because I'm in China, internet have some "problems"
