### ISSUE TITLE
Client ignores play button

### ISSUE THREAD

**Issue by JRubics** [HearthProject/OneClient#67]
When clicking play on any instance (and logging in for the first time) nothing happens. The oneclient console log doesnt report anything. Only when I run the client manually from a terminal, I can see the stack trace there.

https://pastebin.com/hazQEbu3

- OS: Arch Linux (latest kernel)
- Java version: openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

Tested on another machine with the same OS and java version and it worked. Not sure what is causing it since I don't do much Java, but I'll be happy to provide any additional information you need.

Thanks

**Comment by primetoxinz** [comment]
Try this: Edit Instance -> Change Version -> Immediately click Update Instance -> Attempt to launch

**Comment by JRubics** [comment]
It worked for one pack, but for example Colonial Expansion doesn't work. When clicking update instace, I get an error window saying: "An error occurred while installing minecraft" And this stack trace in the console:

`
2017-09-27 00:03:58.517 [Thread-15] ERROR OneClientLogging - An Error has occurred:
java.lang.NullPointerException: null
	at com.hearthproject.oneclient.util.minecraft.MinecraftUtil.installMinecraft(MinecraftUtil.java:131) ~[OneClient.jar:0.0.9.191]
	at com.hearthproject.oneclient.fx.controllers.NewInstanceController.lambda$onCreateButtonPress$3(NewInstanceController.java:159) ~[OneClient.jar:0.0.9.191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
`

**Comment by primetoxinz** [comment]
delete your OneClient/minecraft folder and try again for me

**Comment by JRubics** [comment]
Alright, after deleting the minecraft folder and forcing an instance update it finally worked. Thank you very much

**Comment by primetoxinz** [comment]
No problem, working on a rework no this system so it will be more robust soon :)
