### ISSUE TITLE
Unable to Launch Any Packs

### ISSUE THREAD

**Issue by janagyjr** [HearthProject/OneClient#71]
Installed client yesterday, installed a few packs, tried launching one, nothing.

Unsure what issue is. 

Oneclient version 0.0.11.204

Error log: https://gist.github.com/janagyjr/127431fb683bdd85391434c010412e41

**Comment by kruug** [comment]
Did you let the pack finish downloading before trying to launch?  I ran into that issue because it wasn't intuitive that the pack was still downloading.

**Comment by primetoxinz** [comment]
Why are you commenting on an issue 2 months ago on a project that is no longer supported?

**Comment by kruug** [comment]
OneClient is no longer supported?

**Comment by primetoxinz** [comment]
No, we moved on to an alternative project known as HearthLauncher which is the successor of the OneClient. It is not currently available to the public but it is much better than 1C

**Comment by janagyjr** [comment]
Probably should close this issue.
