### ISSUE TITLE
Installation window TextField is editable

### ISSUE THREAD

**Issue by NillerMedDild** [HearthProject/OneClient#8]
Pretty much the title.

![billede](https://user-images.githubusercontent.com/21295394/29683365-63b969e4-890e-11e7-96e2-e1b24c7a00cd.png)

**Comment by modmuss50** [comment]
Should be fixed in the update, restart the client to get it?

**Comment by NillerMedDild** [comment]
Update went smooth, and the bug is fixed.

**Comment by modmuss50** [comment]
Glad to hear it.
