### ISSUE TITLE
Installation Window

### ISSUE THREAD

**Issue by NillerMedDild** [HearthProject/OneClient#9]
Hey hey!

The installing bar doesn't go all the way, when it has completed the download and installation of a modpack. Also, I feel like there's a bit too much information given while downloading, unless it's a temporary debug thing?
![billede](https://user-images.githubusercontent.com/21295394/29685091-a8c1ed44-8914-11e7-8d8e-53a4cb4dce3b.png)

**Comment by modmuss50** [comment]
Yeah, I think we are going to move the download bar into the main launcher somehow, not sure on the details, but it will get redone soon.

**Comment by NillerMedDild** [comment]
Ah cool, I'll lay off it then :P
